site_name: Redis plug-ins for Grafana
site_url: http://redisgrafana.github.io
edit_uri: https://github.com/RedisGrafana/redisgrafana/edit/main/docs/
repo_url: https://github.com/RedisGrafana/grafana-redis-datasource
repo_name: RedisGrafana/grafana-redis-datasource

theme:
  name: "material"
  language: "en"
  logo: "images/logo-white.png"
  favicon: "images/logo.png"
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  font:
    text: "Roboto"
    code: "Roboto Mono"
  features:
    - navigation.instant
    - navigation.sections
    - navigation.top

nav:
  - "Home": "index.md"
  - "Quickstart": "quickstart.md"
  - "Redis Data Source":
      - "Configuration": "redis-datasource/configuration.md"
      - "Supported commands": "redis-datasource/commands.md"
      - "Streaming": "redis-datasource/streaming.md"
      - "Variables": "redis-datasource/variables.md"
      - "Commands":
          - "INFO": "redis-datasource/redis/INFO.md"
          - "TMSCAN": "redis-datasource/custom/TMSCAN.md"
          - "TS.RANGE": "redis-datasource/redis-timeseries/TS-RANGE.md"
  - "Redis Application plug-in":
      - "Data Sources": "redis-app/datasources.md"
      - "Custom Panels": "redis-app/panels.md"
      - "Dashboards": "redis-app/dashboards.md"
      - "Panels":
          - "Command line interface (CLI)": "redis-app/redis-cli-panel.md"
          - "Command Latency": "redis-app/redis-latency-panel.md"
          - "Keys consuming a lot of memory": "redis-app/redis-keys-panel.md"
          - "RedisGears": "redis-app/redis-gears-panel.md"
  - "Development":
      - "Docker Images": "development/images.md"
      - "Redis Data Source": "development/redis-datasource.md"
      - "Redis Application plug-in": "development/redis-app.md"
      - "Redis Explorer plug-in": "development/redis-explorer.md"
  - "Projects": "projects.md"
  - "FAQ": "faq.md"

markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.snippets
  - toc:
      permalink: true

plugins:
  - search

extra_javascript:
  - javascripts/extra.js
