# Project information
site_name: Redis plug-ins for Grafana
site_url: http://redisgrafana.github.io
site_description: >-
  The Redis plug-ins for Grafana allow users to connect to the Redis databases
  and build dashboards in Grafana to observe and interact with Redis and Application data.

# Repository
repo_name: RedisGrafana/grafana-redis-datasource
repo_url: https://github.com/RedisGrafana/grafana-redis-datasource
edit_uri: https://github.com/RedisGrafana/redisgrafana/edit/main/docs/

# Configuration
theme:
  name: "material"
  language: "en"
  logo: "images/logo-white.png"
  favicon: "images/logo.png"
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  font:
    text: "Roboto"
    code: "Roboto Mono"
  features:
    - navigation.instant
    - navigation.sections
    - navigation.top
  custom_dir: docs/overrides

nav:
  - "Home": "index.md"
  - "Introduction": "intro.md"
  - "Quickstart": "quickstart.md"
  - "Redis Data Source":
      - "Configuration": "redis-datasource/configuration.md"
      - "Streaming": "redis-datasource/streaming.md"
      - "Variables": "redis-datasource/variables.md"
      - "Commands": "redis-datasource/commands.md"
      - "Redis":
          - "GET": "redis-datasource/redis/GET.md"
          - "INFO": "redis-datasource/redis/INFO.md"
          - "TMSCAN": "redis-datasource/custom/TMSCAN.md"
          - "XLEN": "redis-datasource/redis/XLEN.md"
      - "RedisGears":
          - "RG.DUMPREGISTRATIONS": "redis-datasource/redis-gears/RG-DUMPREGISTRATIONS.md"
          - "RG.PYEXECUTE": "redis-datasource/redis-gears/RG-PYEXECUTE.md"
          - "RG.PYSTATS": "redis-datasource/redis-gears/RG-PYSTATS.md"
      - "RedisTimeSeries":
          - "TS.GET": "redis-datasource/redis-timeseries/TS-GET.md"
          - "TS.INFO": "redis-datasource/redis-timeseries/TS-INFO.md"
          - "TS.MRANGE": "redis-datasource/redis-timeseries/TS-MRANGE.md"
          - "TS.QUERYINDEX": "redis-datasource/redis-timeseries/TS-QUERYINDEX.md"
          - "TS.RANGE": "redis-datasource/redis-timeseries/TS-RANGE.md"
  - "Redis Application plug-in":
      - "Overview": "redis-app/overview.md"
      - "Dashboards":
          - "Redis CLI": "redis-app/dashboards/cli.md"
          - "Redis Overview": "redis-app/dashboards/overview.md"
          - "RedisGears": "redis-app/dashboards/redis-gears.md"
      - "Panels":
          - "Command line interface (CLI)": "redis-app/panels/redis-cli-panel.md"
          - "Command Latency": "redis-app/panels/redis-latency-panel.md"
          - "Keys consuming a lot of memory": "redis-app/panels/redis-keys-panel.md"
          - "RedisGears Script Editor": "redis-app/panels/redis-gears-panel.md"
  - "Development":
      - "Docker Images": "development/images.md"
      - "Redis Data Source": "development/redis-datasource.md"
      - "Redis Application plug-in": "development/redis-app.md"
      - "Redis Explorer plug-in": "development/redis-explorer.md"
  - "Projects":
      - "Pop-up Store": "projects/pop-up-store.md"
      - "Plug-ins Statistics": "projects/grafana-stats.md"
  - "Timeline": "timeline.md"
  - "FAQ": "faq.md"

markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.snippets
  - toc:
      permalink: true

plugins:
  - search

extra_javascript:
  - javascripts/extra.js

extra_css:
  - css/extra.css
