site_name: Redis plug-ins for Grafana
site_url: http://redisgrafana.github.io
edit_uri: https://github.com/RedisGrafana/redisgrafana/edit/main/docs/
repo_url: https://github.com/RedisGrafana/grafana-redis-datasource
repo_name: RedisGrafana/grafana-redis-datasource

use_directory_urls: false

theme:
  name: "material"
  language: "en"
  logo: "images/logo.png"
  favicon: "images/logo.png"
  palette:
    primary: "indigo"
    accent: "red"
  font:
    text: "Roboto"
    code: "Roboto Mono"
  feature:
    tabs: false

nav:
  - "Home": "index.md"
  - "Quickstart": "quickstart.md"
  - "Redis Data Source":
      - "Configuration": "redis-datasource/configuration.md"
      - "Supported commands": "redis-datasource/commands.md"
      - "Redis":
          - "INFO": "redis-datasource/INFO.md"
      - "RedisTimeSeries":
          - "TS.RANGE": "redis-datasource/TS-RANGE.md"
  - "Dashboards": "dashboards.md"
  - "Development":
      - "Redis Data Source": "development/redis-datasource.md"
      - "Redis Application plug-in": "development/redis-app.md"

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: False
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - toc:
      permalink: True

plugins:
  - search
  - include:
      src_path: docs/sources
