site_name: Redis plug-ins for Grafana
site_url: http://redisgrafana.github.io
edit_uri: https://github.com/RedisGrafana/redisgrafana/edit/main/docs/
repo_url: https://github.com/RedisGrafana/grafana-redis-datasource
repo_name: RedisGrafana/grafana-redis-datasource

use_directory_urls: false

google_analytics:
  - G-8E4J019JNF
  - auto

theme:
  name: "material"
  language: "en"
  logo: "images/logo-white.png"
  favicon: "images/logo.png"
  palette:
    primary: "indigo"
    accent: "red"
  font:
    text: "Roboto"
    code: "Roboto Mono"
  feature:
    tabs: false

nav:
  - "Home": "index.md"
  - "Quickstart": "quickstart.md"
  - "Redis Data Source":
      - "Configuration": "redis-datasource/configuration.md"
      - "Supported commands": "redis-datasource/commands.md"
      - "Streaming": "redis-datasource/streaming.md"
      - "Commands":
          - "INFO": "redis-datasource/INFO.md"
          - "TMSCAN": "redis-datasource/TMSCAN.md"
          - "TS.RANGE": "redis-datasource/TS-RANGE.md"
  - "Redis Application plug-in":
      - "Custom panels": "redis-app/panels.md"
      - "Dashboards": "redis-app/dashboards.md"
      - "Panels":
          - "Command line interface (CLI)": "redis-app/redis-cli-panel.md"
          - "Command Latency": "redis-app/redis-latency-panel.md"
          - "Keys consuming a lot of memory": "redis-app/redis-keys-panel.md"
          - "RedisGears": "redis-app/redis-gears-panel.md"
  - "Development":
      - "Docker Images": "development/images.md"
      - "Redis Data Source": "development/redis-datasource.md"
      - "Redis Application plug-in": "development/redis-app.md"
      - "Redis Explorer plug-in": "development/redis-explorer.md"
  - "Examples": "examples.md"
  - "FAQ": "faq.md"

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: False
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - toc:
      permalink: True

plugins:
  - search
  - include:
      src_path: docs/sources
